import { prisma } from '@/lib/db/prisma';
import { AIServiceFactory } from '@/lib/ai/service-refactored';
import { getDefaultModel } from '@/lib/ai/config';
import { Prisma } from '@prisma/client';
import { logger } from '@/lib/logger';

const SUMMARY_MODEL =
  process.env.DEBATE_SUMMARY_MODEL ?? getDefaultModel('deepseek', 'chat');

/**
 * 生成并持久化辩论 AI 总结（内部服务，无需认证，供 fire-and-forget 调用）。
 * 与 POST /api/v1/debates/[id]/summary 路由共享同一业务逻辑。
 */
export async function autoGenerateDebateSummary(
  debateId: string
): Promise<void> {
  const debate = await prisma.debate.findUnique({
    where: { id: debateId },
    include: {
      case: {
        select: {
          title: true,
          description: true,
          plaintiffName: true,
          defendantName: true,
        },
      },
      rounds: {
        where: { status: 'COMPLETED' },
        orderBy: { roundNumber: 'asc' },
        include: {
          arguments: {
            orderBy: { createdAt: 'asc' },
            select: { side: true, content: true, legalBasis: true },
          },
        },
      },
    },
  });

  if (!debate || debate.rounds.length === 0) {
    logger.info(
      `[summary-service] 辩论 ${debateId} 无已完成轮次，跳过自动总结`
    );
    return;
  }

  const caseInfo = debate.case;
  const roundsSummary = debate.rounds
    .map(round => {
      const formatSide = (side: 'PLAINTIFF' | 'DEFENDANT') =>
        round.arguments
          .filter(a => a.side === side)
          .map((a, i) => {
            const lb = Array.isArray(a.legalBasis)
              ? (
                  a.legalBasis as Array<{
                    lawName?: string;
                    articleNumber?: string;
                  }>
                )
                  .filter(b => b.lawName)
                  .map(b => `《${b.lawName}》${b.articleNumber}`)
                  .join('、')
              : '';
            return `  ${i + 1}. ${a.content.substring(0, 180)}${lb ? `（法律依据：${lb}）` : ''}`;
          })
          .join('\n') || '  （无）';

      return `### 第${round.roundNumber}轮\n原告：\n${formatSide('PLAINTIFF')}\n被告：\n${formatSide('DEFENDANT')}`;
    })
    .join('\n\n');

  const aiPrompt = `你是资深法律专家，请对以下模拟法庭辩论做客观专业的总结分析。

案件：${caseInfo.title}
原告：${caseInfo.plaintiffName ?? '原告方'}
被告：${caseInfo.defendantName ?? '被告方'}
案情：${(caseInfo.description ?? '').substring(0, 300)}

辩论记录（共${debate.rounds.length}轮已完成）：
${roundsSummary}

请以 JSON 格式输出（不加 markdown 代码块之外的任何文字）：
\`\`\`json
{
  "verdict": "综合评估：从法律论证角度分析哪方更有力，说明主要依据（150字以内）",
  "plaintiffStrengths": ["原告最有力论点1", "原告最有力论点2"],
  "defendantStrengths": ["被告最有力论点1", "被告最有力论点2"],
  "keyLegalIssues": ["本案核心法律争议1", "核心争议2", "核心争议3"],
  "weaknesses": {
    "plaintiff": "原告方论证的主要不足",
    "defendant": "被告方论证的主要不足"
  },
  "recommendation": "对律师备庭的改进建议（100字以内）"
}
\`\`\``;

  const aiService = await AIServiceFactory.getInstance();
  const response = await aiService.chatCompletion({
    model: SUMMARY_MODEL,
    messages: [
      {
        role: 'system',
        content:
          '你是资深法律专家，请以JSON格式输出辩论总结，不要添加任何其他文字。',
      },
      { role: 'user', content: aiPrompt },
    ],
    temperature: 0.3,
    maxTokens: 1500,
  });

  const rawContent = response.choices?.[0]?.message?.content ?? '';

  let summaryData: Record<string, unknown>;
  try {
    const codeMatch = rawContent.match(/```json\s*([\s\S]*?)\s*```/);
    const jsonText = codeMatch
      ? codeMatch[1]
      : (rawContent.match(/\{[\s\S]*\}/)?.[0] ?? '{}');
    summaryData = JSON.parse(jsonText) as Record<string, unknown>;
  } catch {
    summaryData = { verdict: rawContent.substring(0, 600), raw: true };
  }

  const payload = {
    ...summaryData,
    generatedAt: new Date().toISOString(),
    roundCount: debate.rounds.length,
    autoGenerated: true,
  };

  await prisma.debate.update({
    where: { id: debateId },
    data: { summary: payload as unknown as Prisma.InputJsonValue },
  });

  logger.info(
    `[summary-service] 辩论 ${debateId} 自动总结完成（${debate.rounds.length}轮）`
  );
}
